Add feedback
ilsenatorov/kilter-gpt pull request #14
Opened 2024-09-24 13:52 UTC by epivoca

2024-09-25 11:03 UTC, ilsenatorov requested changes

2024-09-25 11:03 UTC, ilsenatorov commented on src/app/README.md
> +│   └── v0
is v0 a version or am I missing something?

2024-09-25 11:03 UTC, ilsenatorov commented on src/app/models/generation.py
> +    # TODO: do we want to generate harder climbs or vice versa limit with softer grades
Probably best to stay within the 5a-8c+ range, the quality would be quite bad further down the line...

2024-09-25 11:03 UTC, ilsenatorov commented on src/app/models/generation.py
> +    temperature: float = Field(description="Responds for randomness of routes generation", default=0.8, ge=0, le=1)
temperature can't be 0, maybe set the lowest to 0.1?

2024-09-25 11:03 UTC, ilsenatorov commented on src/app/models/generation.py
> +    temperature: float = Field(description="Responds for randomness of routes generation", default=0.8, ge=0, le=1)
Actually even 0.3 is a good minimum

2024-09-25 11:03 UTC, ilsenatorov commented on src/app/models/generation.py
> +    id: Optional[str] = Field(description="Id that should be used to send feedback with", default=None)  # TODO: not sure about type, maybe UUID?
Generated routes don't have UUID, maybe sort the holds and use frames as a unique identifier?

2024-09-25 11:03 UTC, ilsenatorov commented on src/app/service/kilter_gpt.py
> +        sys.path.append(str(Path(__file__).parent.parent.parent))
can this be avoided? Maybe install the package with `pip install -e .` or something?

2024-09-25 11:03 UTC, ilsenatorov commented on src/app/service/kilter_gpt.py
> +        model = GPTModel.load_from_wandb(settings.WANDB_MODEL_CHECKPOINT).to("cpu")  # TODO: maybe make device dependent on CUDA existence?
Can do, but generating on CPU takes like 200ms, which is fine...

2024-09-25 14:16 UTC, epivoca commented on src/app/models/generation.py
> +    id: Optional[str] = Field(description="Id that should be used to send feedback with", default=None)  # TODO: not sure about type, maybe UUID?
According to Phil's description of the supabase schemes, it is smth like this:
```sql
CREATE TABLE IF NOT EXISTS public.boards_kilter__climbs (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    layout_id int8 NOT NULL,
    name text NOT NULL,
    description text,
    frames text,
    generated boolean,
    created_at timestamptz DEFAULT now(),
    original_uuid text
);
```

So the idea is to get the climb id from the `insert` operation (it generates in the db automatically) and return it back to the client, so it can be used to save feedback later:
```sql
CREATE TABLE IF NOT EXISTS public.boards_kilter__climb_feedback(
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    climb_id uuid NOT NULL REFERENCES public.boards_kilter__climbs(id) ON DELETE CASCADE,
    user_id int8 NOT NULL,
    type text NOT NULL,
    created_at timestamptz DEFAULT now()
);

```

My bad, didn't provide sql schemes here

2024-09-25 14:18 UTC, epivoca commented on src/app/README.md
> +│   └── v0
Yeah, that's right. It is an api version

2024-09-25 14:30 UTC, epivoca commented on src/app/service/kilter_gpt.py
> +        model = GPTModel.load_from_wandb(settings.WANDB_MODEL_CHECKPOINT).to("cpu")  # TODO: maybe make device dependent on CUDA existence?
Sure

2024-09-28 20:17 UTC, epivoca commented on src/app/service/kilter_gpt.py
> +        sys.path.append(str(Path(__file__).parent.parent.parent))
Actually, decision to put all into src folder was a bad decision. Finally realised what a tricky MRO behavior it causes.

I decided to restructure packages, so app now is part of kiltergpt package, which seems more idiomatic to me:
if we want to run model as webservice, we can simply `from kiltergpt.app import ...` and so on. Now web is just an option.

2024-10-01 18:49 UTC, merged